services:
  - type: web
    name: profile-chatbot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker api_server:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
